#!/usr/bin/env bash
# Get named var (usage: get "VAR_NAME")

get() {
  echo "${!1}"
}

# Feature detection

can-sudo() {
  /usr/bin/sudo -v
}

is-macos() {
  [[ "$OSTYPE" =~ ^darwin ]] || return 1;
}

is-executable() {
  type "$1" > /dev/null 2>&1 || return 1;
}

is-supported() {
  if [ $# -eq 1 ]; then
    if eval "$1" > /dev/null 2>&1; then true; else false; fi
  else
    if eval "$1" > /dev/null 2>&1; then
      echo -n "$2"
    else
      echo -n "$3"
    fi
  fi
}

can-apt() {
  is-executable /usr/bin/apt
}

can-dnf() {
  is-executable /usr/bin/dnf
}

can-yum() {
  is-executable /usr/bin/yum
}

can-snap() {
  is-executable /usr/bin/snap
}

# Add to path

prepend-path() {
  if [ -d "$1" ]; then
    echo "path: $(tput setaf 2)✓$(tput sgr 0) $1"
    PATH="$1:$PATH"
  else
    echo -e "path: $(tput setaf 1)✘$(tput sgr 0) $1"
    return 1
  fi
}

# Remove duplicates (preserving prepended items)
# Source: http://unix.stackexchange.com/a/40755

dedupe-path() {
  PATH=$(echo -n "$PATH" | awk -v RS=: '{ if (!arr[$0]++) {printf("%s%s",!ln++?"":":",$0)}}')
}

# Check if in path

in-path() {
  [[ :"$PATH": == *:"$1":* ]]
}

# brew detection

can-brew() {
  is-executable brew
}

is-brewed() {
  brew list "$1" > /dev/null 2>&1 || return 1;
}

soutdated() {
  # Check system package manager
  if is-macos; then
    echo "Checking softwareupdate..."
    softwareupdate --list
  elif can-apt; then
    echo "Checking apt..."
    sudo apt update && apt list --upgradable
  fi

  # Check homebrew packages
  if can-brew; then
    echo "Checking brew..."
    brew update && brew outdated
    # if is-macos; then
    #   echo "Checking brew cask..."
    #   brew cask outdated
    # else
    #   echo "Not on a Mac, bro! Skipping brew cask..."
    # fi
  fi
}

supdate() {
  # Update system packages
  if is-macos; then
    echo "Updating software..."
    sudo softwareupdate --install --all
  elif can-apt; then
    echo "Updating apt..."
    sudo apt update && sudo apt upgrade
  fi

  # Refresh snaps
  if can-snap; then
    echo "Refreshing snaps..."
    sudo snap Refresh
  fi

  # Update brew packages
  if can-brew; then
    echo "Updating brew..."
    brew update && brew upgrade
    # if is-macos; then
    #   echo "Updating brew cask..."
    #   brew cask upgrade
    # else
    #   echo "Not on a Mac, bro! Skipping brew cask..."
    # fi
  fi
}

# Update config file

set-config() {
  local KEY="$1"
  local VALUE="$2"
  local FILE="$3"
  touch "$FILE"
  if grep -q "$1=" "$FILE"; then
    sed "s@$KEY=.*@$KEY=\"$VALUE\"@" -i "$FILE"
  else
    echo "export $KEY=$VALUE" >> "$FILE"
  fi
}

# Extract many types of compressed packages
# Credit: http://nparikh.org/notes/zshrc.txt
extract() {
  if [ -f "$1" ]; then
    case "$1" in
      *.tar.bz2)  tar -jxvf "$1"                        ;;
      *.tar.gz)   tar -zxvf "$1"                        ;;
      *.bz2)      bunzip2 "$1"                          ;;
      *.gz)       gunzip "$1"                           ;;
      *.tar)      tar -xvf "$1"                         ;;
      *.tbz2)     tar -jxvf "$1"                        ;;
      *.tgz)      tar -zxvf "$1"                        ;;
      *.zip)      unzip "$1"                            ;;
      *.ZIP)      unzip "$1"                            ;;
      *.pax)      cat "$1" | pax -r                     ;;
      *.pax.Z)    uncompress "$1" --stdout | pax -r     ;;
      *.Z)        uncompress "$1"                       ;;
      *) echo "'$1' cannot be extracted/mounted via extract()" ;;
    esac
  else
     echo "'$1' is not a valid file to extract"
  fi
}

# https://github.com/unicorn-fail/version_compare
# Version compare
function version_compare () {
  # Default to a failed comparison result.
  local -i result=1;

  # Ensure there are two versions to compare.
  [ $# -lt 2 ] || [ -z "${1}" ] || [ -z "${2}" ] && echo "${FUNCNAME[0]} requires a minimum of two arguments to compare versions." &>/dev/stderr && return ${result}

  # Determine the operation to perform, if any.
  local op="${3}"

  # Convert passed versions into values for comparison.
  local v1=$(version_compare_convert "${1}")
  local v2=$(version_compare_convert "${2}")

  # Immediately return when comparing version equality (which doesn't require sorting).
  if [ -z "${op}" ]; then
    [ "${v1}" == "${v2}" ] && echo 0 && return;
  else
    if [ "${op}" == "!=" ] || [ "${op}" == "<>" ] || [ "${op}" == "ne" ]; then
      if [ "${v1}" != "${v2}" ]; then let result=0; fi;
      return ${result};
    elif [ "${op}" == "=" ] || [ "${op}" == "==" ] || [ "${op}" == "eq" ]; then
      if [ "${v1}" == "${v2}" ]; then let result=0; fi;
      return ${result};
    elif [ "${op}" == "le" ] || [ "${op}" == "<=" ] || [ "${op}" == "ge" ] || [ "${op}" == ">=" ] && [ "${v1}" == "${v2}" ]; then
      if [ "${v1}" == "${v2}" ]; then let result=0; fi;
      return ${result};
    fi
  fi

  # If we get to this point, the versions should be different.
  # Immediately return if they're the same.
  [ "${v1}" == "${v2}" ] && return ${result}

  local sort='sort'

  # If only one version has a pre-release label, reverse sorting so
  # the version without one can take precedence.
  [[ "${v1}" == *"-"* ]] && [[ "${v2}" != *"-"* ]] || [[ "${v2}" == *"-"* ]] && [[ "${v1}" != *"-"* ]] && sort="${sort} -r"

  # Sort the versions.
  local -a sorted=($(printf "%s\n%s" "${v1}" "${v2}" | ${sort}))

  # No operator passed, indicate which direction the comparison leans.
  if [ -z "${op}" ]; then
    if [ "${v1}" == "${sorted[0]}" ]; then echo -1; else echo 1; fi
    return
  fi

  case "${op}" in
    "<" | "lt" | "<=" | "le") if [ "${v1}" == "${sorted[0]}" ]; then let result=0; fi;;
    ">" | "gt" | ">=" | "ge") if [ "${v1}" == "${sorted[1]}" ]; then let result=0; fi;;
  esac

  return ${result}
}

# https://github.com/unicorn-fail/version_compare
# Converts a version string to an integer that is used for comparison purposes.
function version_compare_convert () {
  local version="${@}"

  # Remove any build meta information as it should not be used per semver spec.
  version="${version%+*}"

  # Extract any pre-release label.
  local prerelease
  [[ "${version}" = *"-"* ]] && prerelease=${version##*-}
  [ -n "${prerelease}" ] && prerelease="-${prerelease}"

  version="${version%%-*}"

  # Separate version (minus pre-release label) into an array using periods as the separator.
  local OLDIFS="${IFS}" && local IFS=. && version=("${version%-*}") && IFS="${OLDIFS}"

  # Unfortunately, we must use sed to strip of leading zeros here.
  local major=$(echo "${version[0]:=0}" | sed 's/^0*//')
  local minor=$(echo "${version[1]:=0}" | sed 's/^0*//')
  local patch=$(echo "${version[2]:=0}" | sed 's/^0*//')
  local build=$(echo "${version[3]:=0}" | sed 's/^0*//')

  # Combine the version parts and pad everything with zeros, except major.
  printf "%s%04d%04d%04d%s\n" "${major}" "${minor}" "${patch}" "${build}" "${prerelease}"
}
