# https://starship.rs/config/
# Disable the newline at the start of the prompt
add_newline = false
# Overwrite a default_prompt_order and  use custom prompt_order
format = """
  $git_branch\
  $git_commit\
  $git_state\
  $git_status\
  $hg_branch\
  $package\
  $dotnet\
  $elixir\
  $elm\
  $golang\
  $haskell\
  $java\
  $nodejs\
  $php\
  $python\
  $ruby\
  $rust\
  $terraform\
  $nix_shell\
  $conda\
  $memory_usage\
  $aws\
  $env_var\
  $crystal\
  $line_break\

  $username\
  $hostname\
  $kubernetes\
  $directory\
  $line_break\

  $jobs\
  $battery\
  $time\
  $cmd_duration\
  $character\
"""
# Wait 60 milliseconds for starship to check files under the current directory.
scan_timeout = 60
# Wait 1000 milliseconds for commands executed by starship to return.
command_timeout = 1500

[character]
success_symbol = "[✔❯](green)"
error_symbol = "[✘❯](red)"

[directory]
style = "cyan"
truncation_length = 0
truncate_to_repo = false

[git_branch]
style = "purple"
format = "[$symbol$branch]($style) "

[git_commit]
style = "green"

[git_state]
style = "yellow"

[git_status]
style = "red"

[hostname]
ssh_only = false
style = "blue"
disabled = false

[java]
style = "red"

[line_break]
disabled = false

[nodejs]
style = "yellow"

[package]
style = "cyan"

[python]
style = "yellow"

[time]
disabled = false
style = "yellow"

[username]
style_root = "bold red"
style_user = "blue"
show_always = true
disabled = false
